"use client"
import {useEffect,useState} from "react"
import {LANGUAGE_APPLIED_EVENT,activeUiLocale,type SupportedUiLocale} from "@/lib/locale-preferences"
const t=(l:SupportedUiLocale,nl:string,en:string,fr:string,de:string)=>({nl,en,fr,de}[l])
const KEY="uptilldawn-training-workflow-v3"
export function SandboxBriefings(){
 const [l,setL]=useState<SupportedUiLocale>(()=>typeof window==="undefined"?"nl":activeUiLocale())
 const [read,setRead]=useState(()=>{if(typeof window==="undefined")return false;try{return !!JSON.parse(sessionStorage.getItem(KEY)||"{}").briefingRead}catch{return false}})
 useEffect(()=>{const apply=()=>setL(activeUiLocale());addEventListener(LANGUAGE_APPLIED_EVENT,apply);return()=>removeEventListener(LANGUAGE_APPLIED_EVENT,apply)},[])
 const acknowledge=()=>{let s={};try{s=JSON.parse(sessionStorage.getItem(KEY)||"{}")}catch{};sessionStorage.setItem(KEY,JSON.stringify({...s,briefingRead:true}));setRead(true)}
 return <main className="space-y-5 p-4 md:p-8">
  <div><h1 className="text-3xl font-black">{t(l,"Briefing & checklists","Briefing & checklists","Briefing & checklists","Briefing & Checklisten")}</h1><p className="text-sm text-muted-foreground">{t(l,"Lees de briefing voor je toegewezen shift en bevestig dat je de instructies hebt gelezen.","Read the briefing for your assigned shift and confirm that you have read the instructions.","Lisez le briefing de votre shift attribué et confirmez que vous avez lu les instructions.","Lies das Briefing für deine zugewiesene Schicht und bestätige, dass du die Anweisungen gelesen hast.")}</p></div>
  <article className="space-y-3 rounded-xl border p-4">
   <div><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{t(l,"UpTillDawn Trainingsavond · Bar / Toog","UpTillDawn Training Night · Bar / Counter","Soirée d’entraînement UpTillDawn · Bar / Comptoir","UpTillDawn Trainingsabend · Bar / Theke")}</p><h2 className="mt-1 text-xl font-bold">{t(l,"Shiftbriefing · v1","Shift briefing · v1","Briefing du shift · v1","Schichtbriefing · v1")}</h2><p className="mt-1 text-xs text-muted-foreground">10/10/2026 · 20:00 → 11/10/2026 · 04:00</p></div>
   <div className="space-y-3 text-sm"><p>{t(l,"Meld je bij de verantwoordelijke van Bar / Toog vóór je shift start. Controleer samen de werkpost en de prijslijst.","Report to the Bar / Counter responsible lead before your shift starts. Check the workplace and price list together.","Présentez-vous au responsable du Bar / Comptoir avant le début de votre shift. Vérifiez ensemble le poste et la liste des prix.","Melde dich vor Beginn deiner Schicht bei der verantwortlichen Person für Bar / Theke. Prüft gemeinsam den Arbeitsplatz und die Preisliste.")}</p><ul className="list-disc space-y-1 pl-5"><li>{t(l,"Controleer of de werkpost volledig en veilig is.","Check that the workplace is complete and safe.","Vérifiez que le poste de travail est complet et sûr.","Prüfe, ob der Arbeitsplatz vollständig und sicher ist.")}</li><li>{t(l,"Gebruik alleen de actuele prijslijst.","Use only the current price list.","Utilisez uniquement la liste des prix actuelle.","Verwende nur die aktuelle Preisliste.")}</li><li>{t(l,"Meld ontbrekend of beschadigd materiaal aan de verantwoordelijke.","Report missing or damaged equipment to the responsible lead.","Signalez le matériel manquant ou endommagé au responsable.","Melde fehlendes oder beschädigtes Material der verantwortlichen Person.")}</li><li>{t(l,"Gebruik Help/Incidenten wanneer er tijdens je shift een probleem is.","Use Help/Incidents if there is a problem during your shift.","Utilisez Aide/Incidents en cas de problème pendant votre shift.","Nutze Hilfe/Vorfälle, wenn während deiner Schicht ein Problem auftritt.")}</li></ul><div className="rounded-xl border bg-muted/20 p-3"><p className="font-semibold">{t(l,"Prijslijst Bar / Toog","Bar / Counter price list","Liste des prix Bar / Comptoir","Preisliste Bar / Theke")}</p><p className="mt-1 text-xs text-muted-foreground">{t(l,"Voorbeeldbijlage · actuele prijslijst voor deze shift","Example attachment · current price list for this shift","Pièce jointe d’exemple · liste des prix actuelle pour ce shift","Beispielanhang · aktuelle Preisliste für diese Schicht")}</p></div></div>
   {!read?<button type="button" onClick={acknowledge} className="rounded-xl border p-3 font-bold ring-4 ring-violet-500/40">{t(l,"INSTRUCTIE GELEZEN","INSTRUCTION READ","INSTRUCTION LUE","ANWEISUNG GELESEN")}</button>:<div className="space-y-3"><p>{t(l,"INSTRUCTIE GELEZEN","INSTRUCTION READ","INSTRUCTION LUE","ANWEISUNG GELESEN")}</p><button type="button" onClick={()=>{let s={};try{s=JSON.parse(sessionStorage.getItem(KEY)||"{}")}catch{};sessionStorage.setItem(KEY,JSON.stringify({...s,navTarget:"operations"}));dispatchEvent(new CustomEvent("uptilldawn-training-nav-target",{detail:{target:"operations"}}))}} className="rounded-xl border p-3 font-bold ring-4 ring-violet-500/40">{t(l,"NAAR CHECK-IN","GO TO CHECK-IN","ALLER AU CHECK-IN","ZUM CHECK-IN")}</button></div>}
  </article>
 </main>
}
