"use client"
import {useEffect,useState} from "react"
import {LANGUAGE_APPLIED_EVENT,parseUiLocale} from "@/lib/locale-preferences"

type L="nl"|"en"|"fr"|"de"
const tr=(l:L,nl:string,en:string,fr:string,de:string)=>({nl,en,fr,de}[l])
type Phase="ready"|"checked"|"working"|"break"|"done"

export function SandboxEvent({userName,role}:{userName:string;role:string}){
 const [l,setL]=useState<L>("nl"),[phase,setPhase]=useState<Phase>("ready"),[note,setNote]=useState("")
 useEffect(()=>{const apply=()=>setL((parseUiLocale(document.documentElement.lang)||"nl") as L);apply();addEventListener(LANGUAGE_APPLIED_EVENT,apply);return()=>removeEventListener(LANGUAGE_APPLIED_EVENT,apply)},[])
 const explain=(text:string)=>{setNote(text);window.setTimeout(()=>setNote(""),4200)}
 const action=()=>{
  if(phase==="ready"){setPhase("checked");explain(tr(l,"Je bent ingecheckt. De verantwoordelijke ziet je nu als aanwezig.","You are checked in. The responsible lead now sees you as present.","Vous êtes enregistré. Le responsable vous voit maintenant comme présent.","Du bist eingecheckt. Die verantwortliche Person sieht dich jetzt als anwesend."));return}
  if(phase==="checked"){setPhase("working");explain(tr(l,"Je werkklok loopt nu. Pauzes worden apart geregistreerd.","Your work timer is now running. Breaks are registered separately.","Votre temps de travail est maintenant en cours. Les pauses sont enregistrées séparément.","Deine Arbeitszeit läuft jetzt. Pausen werden separat erfasst."));return}
  if(phase==="working"){setPhase("break");explain(tr(l,"Je pauze is gestart. Na de pauze loopt je werkklok verder.","Your break has started. Your work timer continues afterwards.","Votre pause a commencé. Votre temps de travail reprend ensuite.","Deine Pause hat begonnen. Danach läuft deine Arbeitszeit weiter."));return}
  if(phase==="break"){setPhase("working");explain(tr(l,"Pauze beëindigd. Je bent opnieuw aan het werk.","Break ended. You are working again.","Pause terminée. Vous travaillez à nouveau.","Pause beendet. Du arbeitest wieder."));return}
  setPhase("done")
 }
 const label=phase==="ready"?tr(l,"INCHECKEN","CHECK IN","CHECK-IN","EINCHECKEN"):phase==="checked"?tr(l,"START WERK","START WORK","COMMENCER","ARBEIT STARTEN"):phase==="working"?tr(l,"START PAUZE","START BREAK","COMMENCER LA PAUSE","PAUSE STARTEN"):tr(l,"STOP PAUZE","END BREAK","TERMINER LA PAUSE","PAUSE BEENDEN")
 return <main className="space-y-4 p-4 pb-28 md:p-8">
  <section className="rounded-2xl border bg-card p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-violet-400">{tr(l,"LOPEND EVENEMENT","LIVE EVENT","ÉVÉNEMENT EN COURS","LAUFENDES EVENT")}</p><h1 className="text-2xl font-black">{tr(l,"UpTillDawn Trainingsavond","UpTillDawn Training Night","Soirée d’entraînement UpTillDawn","UpTillDawn Trainingsabend")}</h1><p className="text-sm text-muted-foreground">{tr(l,"Vanavond · 20:00–04:00 · Trainingslocatie","Tonight · 20:00–04:00 · Training Venue","Ce soir · 20:00–04:00 · Lieu d’entraînement","Heute Abend · 20:00–04:00 · Trainingsort")}</p></div><span className="rounded-full border px-3 py-1 text-xs font-bold">{tr(l,"ACTIEF","LIVE","ACTIF","AKTIV")}</span></div></section>
  <section className="grid gap-3 md:grid-cols-3"><article className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted-foreground">{tr(l,"Mijn werkplek","My workplace","Mon poste","Mein Arbeitsplatz")}</p><p className="text-xl font-black">{tr(l,"Hoofdbar","Main Bar","Bar principal","Hauptbar")}</p><p>{role==="responsible_lead"?tr(l,"Verantwoordelijke","Responsible","Responsable","Verantwortlich"):tr(l,"Barpersoneel","Bar staff","Personnel du bar","Barpersonal")}</p></article><article className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted-foreground">{tr(l,"Mijn shift","My shift","Mon shift","Meine Schicht")}</p><p className="text-xl font-black">20:00–04:00</p><p>{phase==="working"?tr(l,"Aan het werk","Working","Au travail","Bei der Arbeit"):phase==="break"?tr(l,"Pauze","Break","Pause","Pause"):tr(l,"Klaar om te starten","Ready to start","Prêt à commencer","Startbereit")}</p></article><article className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted-foreground">{tr(l,"Briefing","Briefing","Briefing","Briefing")}</p><p className="font-black">{tr(l,"Bevestigd","Confirmed","Confirmé","Bestätigt")}</p><p className="text-sm">{tr(l,"Bar klaar om 19:45. Controleer voorraad en prijslijst.","Bar ready by 19:45. Check stock and price list.","Bar prêt à 19:45. Vérifiez le stock et la liste des prix.","Bar bis 19:45 bereit. Bestand und Preisliste prüfen.")}</p></article></section>
  <section className="rounded-2xl border bg-card p-4"><h2 className="font-black">{tr(l,"Live team · Hoofdbar","Live team · Main Bar","Équipe en direct · Bar principal","Live-Team · Hauptbar")}</h2><div className="mt-3 space-y-2"><p>{userName} · {phase==="working"?tr(l,"Aan het werk","Working","Au travail","Bei der Arbeit"):phase==="break"?tr(l,"Pauze","Break","Pause","Pause"):tr(l,"Aanwezig","Present","Présent","Anwesend")}</p><p>{tr(l,"Alex Demo","Alex Demo","Alex Demo","Alex Demo")} · {tr(l,"Aan het werk","Working","Au travail","Bei der Arbeit")} · 00:42:18</p><p>{tr(l,"Sam Demo","Sam Demo","Sam Demo","Sam Demo")} · {tr(l,"Pauze","Break","Pause","Pause")} · 00:18:07</p></div></section>
  <section className="grid gap-3 md:grid-cols-2"><article className="rounded-2xl border bg-card p-4"><h2 className="font-black">{tr(l,"Taken","Tasks","Tâches","Aufgaben")}</h2><p className="mt-2">✓ {tr(l,"Koelkasten vullen","Stock fridges","Remplir les frigos","Kühlschränke auffüllen")}</p><p>○ {tr(l,"Prijslijst controleren","Check price list","Vérifier la liste des prix","Preisliste prüfen")}</p></article><article className="rounded-2xl border bg-card p-4"><h2 className="font-black">{tr(l,"Inventaris","Inventory","Inventaire","Inventar")}</h2><p className="mt-2">✓ {tr(l,"Bekers","Cups","Gobelets","Becher")} · 800</p><p>✓ {tr(l,"Betaalterminal","Payment terminal","Terminal de paiement","Zahlungsterminal")} · 2</p></article></section>
  <button type="button" onClick={action} className="w-full rounded-xl bg-violet-600 p-4 font-black text-white">{label}</button>
  {note&&<div className="fixed inset-x-3 bottom-[calc(5rem+env(safe-area-inset-bottom))] z-[160] rounded-2xl border border-violet-500/40 bg-background p-4 shadow-2xl"><p className="font-bold">{note}</p><button type="button" onClick={()=>setNote("")} className="mt-3 rounded-lg border px-3 py-2 text-sm font-bold">{tr(l,"BEGREPEN","GOT IT","COMPRIS","VERSTANDEN")}</button></div>}
 </main>
}