"use client"
import {useEffect,useState} from "react"
import {LANGUAGE_APPLIED_EVENT,activeUiLocale,type SupportedUiLocale} from "@/lib/locale-preferences"

const t=(l:SupportedUiLocale,nl:string,en:string,fr:string,de:string)=>({nl,en,fr,de}[l])
export function SandboxWorkplaces(){
 const [l,setL]=useState<SupportedUiLocale>("nl")
 const [briefingTarget,setBriefingTarget]=useState(false)
 const [preferred,setPreferred]=useState("Bar/Toog")
 useEffect(()=>{const apply=()=>setL(activeUiLocale());apply();addEventListener(LANGUAGE_APPLIED_EVENT,apply);return()=>removeEventListener(LANGUAGE_APPLIED_EVENT,apply)},[])
 useEffect(()=>{const frame=requestAnimationFrame(()=>setPreferred(sessionStorage.getItem("uptilldawn-training-preferred-workplace")||"Bar/Toog"));return()=>cancelAnimationFrame(frame)},[])
 return <main id="werkplaatsbeheer" className="scroll-mt-24 space-y-5 p-4 md:p-8">
  <div><h1 className="text-3xl font-black">{t(l,"Werkplaatsen & shifts","Workplaces & shifts","Postes de travail & shifts","Arbeitsplätze & Schichten")}</h1><p className="text-sm text-muted-foreground">{t(l,"Bekijk je toegewezen werkplek, shifturen en bevestig of weiger je dienst vanuit hetzelfde scherm.","View your assigned workplace and shift hours, and accept or decline your shift from the same screen.","Consultez votre poste de travail et vos heures de shift, puis acceptez ou refusez votre shift depuis le même écran.","Sieh deinen zugewiesenen Arbeitsplatz und deine Schichtzeiten und bestätige oder lehne deine Schicht im selben Bildschirm ab.")}</p></div>
  <article className="rounded-2xl border border-violet-500/70 p-4">
   <div className="flex items-start justify-between gap-3"><div><b>{preferred}</b><p className="text-sm text-muted-foreground">{t(l,"UpTillDawn Trainingsavond","UpTillDawn Training Night","Soirée d’entraînement UpTillDawn","UpTillDawn Trainingsabend")}</p><p className="mt-1 text-sm text-muted-foreground">{t(l,"De trainingsshift gebruikt de werkplekvoorkeur uit je profiel.","The training shift uses the workplace preference from your profile.","Le shift d’entraînement utilise la préférence de poste de votre profil.","Die Trainingsschicht verwendet die Arbeitsplatzpräferenz aus deinem Profil.")}</p></div><span className="rounded-full border px-2 py-1 text-xs">{t(l,"ACTIEF","ACTIVE","ACTIF","AKTIV")}</span></div>
   <section className="mt-3 rounded-xl border p-3"><p className="font-semibold">{t(l,"Jouw shift","Your shift","Votre shift","Deine Schicht")}</p><p className="mt-1 text-sm">10/10/2026 · 20:00 → 11/10/2026 · 04:00</p><p className="text-sm text-muted-foreground">{t(l,"Functie op je voorkeurswerkplek","Role at your preferred workplace","Fonction à votre poste préféré","Funktion an deinem bevorzugten Arbeitsplatz")}</p><span className="mt-2 inline-flex rounded-full border border-emerald-500/50 px-2 py-1 text-xs font-bold text-emerald-600">{t(l,"TOEGEWEZEN","ASSIGNED","ASSIGNÉ","ZUGEWIESEN")}</span></section>
   <section className="mt-3 rounded-xl border p-3"><p className="font-semibold">{t(l,"Verantwoordelijke","Responsible lead","Responsable","Verantwortliche Person")}</p><p className="mt-2 text-sm">{t(l,"Demo Verantwoordelijke","Demo Responsible","Responsable démo","Demo-Verantwortliche")}</p></section>
   <section className="mt-3 rounded-xl border p-3"><p className="font-semibold">{t(l,"Briefing","Briefing","Briefing","Briefing")}</p><p className="mt-1 text-sm text-muted-foreground">{t(l,"Je briefing is beschikbaar via de navigatie.","Your briefing is available from the navigation.","Votre briefing est disponible via la navigation.","Dein Briefing ist über die Navigation verfügbar.")}</p>{!briefingTarget?<button type="button" onClick={()=>{let s={};try{s=JSON.parse(sessionStorage.getItem("uptilldawn-training-workflow-v3")||"{}")}catch{};sessionStorage.setItem("uptilldawn-training-workflow-v3",JSON.stringify({...s,navTarget:"briefings"}));dispatchEvent(new CustomEvent("uptilldawn-training-nav-target",{detail:{target:"briefings"}}));setBriefingTarget(true)}} className="mt-3 rounded-lg bg-violet-600 px-3 py-2 text-sm font-semibold text-white">{t(l,"Toon waar Briefing staat","Show where Briefing is","Afficher où se trouve Briefing","Zeige, wo Briefing ist")}</button>:<p className="mt-3 text-sm font-semibold">{t(l,"Gebruik nu het gemarkeerde pijltje onderaan en kies daarna Briefing.","Use the highlighted arrow at the bottom, then choose Briefing.","Utilisez maintenant la flèche surlignée en bas, puis choisissez Briefing.","Nutze jetzt den markierten Pfeil unten und wähle danach Briefing.")}</p>}</section>
  </article>
 </main>
}
