"use client"
import {useEffect,useState} from "react"
import {LANGUAGE_APPLIED_EVENT,parseUiLocale} from "@/lib/locale-preferences"

type L="nl"|"en"|"fr"|"de"
type Stage="event"|"availability"|"assigned"|"briefing"|"checkin"|"working"|"break"|"resumed"|"finished"
type State={stage:Stage;briefing:boolean}
const tr=(l:L,nl:string,en:string,fr:string,de:string)=>({nl,en,fr,de}[l])
const KEY="uptilldawn-training-workflow-v2"

export function SandboxEvent({userName,role}:{userName:string;role:string}){
 const [l,setL]=useState<L>("nl"),[state,setState]=useState<State>(()=>{if(typeof window==="undefined")return {stage:"event",briefing:false};try{const saved=sessionStorage.getItem(KEY);return saved?JSON.parse(saved):{stage:"event",briefing:false}}catch{return {stage:"event",briefing:false}}}),[note,setNote]=useState("")
 useEffect(()=>{const apply=()=>setL((parseUiLocale(document.documentElement.lang)||"nl") as L);apply();addEventListener(LANGUAGE_APPLIED_EVENT,apply);return()=>removeEventListener(LANGUAGE_APPLIED_EVENT,apply)},[])
 const save=(next:State)=>{setState(next);sessionStorage.setItem(KEY,JSON.stringify(next))}
 const explain=(text:string)=>setNote(text)
 const advance=(stage:Stage,message:string)=>{save({...state,stage});explain(message)}
 const workplace=tr(l,"Hoofdbar","Main Bar","Bar principal","Hauptbar")
 const assigned=["assigned","briefing","checkin","working","break","resumed","finished"].includes(state.stage)
 const action=()=>{
  if(state.stage==="event"){advance("availability",tr(l,"Dit is een beschikbaar evenement. Open een evenement altijd eerst om datum, locatie en praktische informatie te controleren.","This is an available event. Always open an event first to check the date, location and practical information.","Ceci est un événement disponible. Ouvrez toujours l’événement pour vérifier la date, le lieu et les informations pratiques.","Dies ist ein verfügbares Event. Öffne es zuerst, um Datum, Ort und praktische Informationen zu prüfen."));return}
  if(state.stage==="availability"){advance("assigned",tr(l,"Je beschikbaarheid is geregistreerd. Voor deze opleiding krijg je automatisch een passende shift op basis van je werkplekvoorkeuren.","Your availability is registered. For this training you are automatically assigned a suitable shift based on your workplace preferences.","Votre disponibilité est enregistrée. Pour cette formation, un shift adapté vous est automatiquement attribué selon vos préférences de poste.","Deine Verfügbarkeit ist registriert. Für dieses Training erhältst du automatisch eine passende Schicht anhand deiner Arbeitsplatzpräferenzen."));return}
  if(state.stage==="assigned"){advance("briefing",tr(l,"Je bent toegewezen aan de Hoofdbar. Voor je shift moet je eerst de briefing openen en bevestigen.","You are assigned to the Main Bar. Before your shift, open and confirm the briefing.","Vous êtes affecté au Bar principal. Avant votre shift, ouvrez et confirmez le briefing.","Du bist der Hauptbar zugeteilt. Öffne und bestätige vor deiner Schicht das Briefing."));return}
  if(state.stage==="briefing"){save({stage:"checkin",briefing:true});explain(tr(l,"Briefing bevestigd. Bij aankomst check je in bij je verantwoordelijke voordat je het werk start.","Briefing confirmed. On arrival, check in with your responsible lead before starting work.","Briefing confirmé. À votre arrivée, enregistrez-vous auprès de votre responsable avant de commencer.","Briefing bestätigt. Bei der Ankunft checkst du bei der verantwortlichen Person ein, bevor du arbeitest."));return}
  if(state.stage==="checkin"){advance("working",tr(l,"Je bent ingecheckt en je werkklok loopt. Je verantwoordelijke ziet je nu als actief.","You are checked in and your work timer is running. Your responsible lead now sees you as active.","Vous êtes enregistré et votre temps de travail est lancé. Votre responsable vous voit maintenant comme actif.","Du bist eingecheckt und deine Arbeitszeit läuft. Die verantwortliche Person sieht dich jetzt als aktiv."));return}
  if(state.stage==="working"){advance("break",tr(l,"Pauze gestart. Pauzetijd wordt apart geregistreerd en telt niet als actieve werktijd.","Break started. Break time is registered separately and does not count as active work time.","Pause commencée. Le temps de pause est enregistré séparément et ne compte pas comme temps de travail actif.","Pause gestartet. Pausenzeit wird separat erfasst und zählt nicht als aktive Arbeitszeit."));return}
  if(state.stage==="break"){advance("resumed",tr(l,"Pauze beëindigd. Je werkklok loopt opnieuw verder.","Break ended. Your work timer is running again.","Pause terminée. Votre temps de travail reprend.","Pause beendet. Deine Arbeitszeit läuft weiter."));return}
  if(state.stage==="resumed"){advance("finished",tr(l,"Je shift is gestopt. Controleer daarna je uren en dien je timesheet in.","Your shift is stopped. Next, check your hours and submit your timesheet.","Votre shift est terminé. Vérifiez ensuite vos heures et envoyez votre feuille de temps.","Deine Schicht ist beendet. Prüfe danach deine Stunden und reiche den Stundenzettel ein."))}
 }
 const button=state.stage==="event"?tr(l,"OPEN DEMO-EVENT","OPEN DEMO EVENT","OUVRIR L’ÉVÉNEMENT DÉMO","DEMO-EVENT ÖFFNEN"):state.stage==="availability"?tr(l,"IK KAN","I CAN","JE PEUX","ICH KANN"):state.stage==="assigned"?tr(l,"OPEN MIJN SHIFT","OPEN MY SHIFT","OUVRIR MON SHIFT","MEINE SCHICHT ÖFFNEN"):state.stage==="briefing"?tr(l,"BEVESTIG BRIEFING","CONFIRM BRIEFING","CONFIRMER LE BRIEFING","BRIEFING BESTÄTIGEN"):state.stage==="checkin"?tr(l,"INCHECKEN EN START WERK","CHECK IN AND START WORK","CHECK-IN ET COMMENCER","EINCHECKEN UND ARBEIT STARTEN"):state.stage==="working"?tr(l,"START PAUZE","START BREAK","COMMENCER LA PAUSE","PAUSE STARTEN"):state.stage==="break"?tr(l,"STOP PAUZE","END BREAK","TERMINER LA PAUSE","PAUSE BEENDEN"):state.stage==="resumed"?tr(l,"STOP WERK","STOP WORK","ARRÊTER LE TRAVAIL","ARBEIT BEENDEN"):tr(l,"OPLEIDING VOLTOOID","TRAINING COMPLETED","FORMATION TERMINÉE","TRAINING ABGESCHLOSSEN")
 return <main className="space-y-4 p-4 pb-28 md:p-8">
  <section className="rounded-2xl border bg-card p-4"><p className="text-xs font-black uppercase tracking-wider text-violet-400">{state.stage==="event"||state.stage==="availability"?tr(l,"BESCHIKBAAR DEMO-EVENT","AVAILABLE DEMO EVENT","ÉVÉNEMENT DÉMO DISPONIBLE","VERFÜGBARES DEMO-EVENT"):tr(l,"MIJN DEMO-EVENT","MY DEMO EVENT","MON ÉVÉNEMENT DÉMO","MEIN DEMO-EVENT")}</p><h1 className="text-2xl font-black">{tr(l,"UpTillDawn Trainingsavond","UpTillDawn Training Night","Soirée d’entraînement UpTillDawn","UpTillDawn Trainingsabend")}</h1><p className="text-sm text-muted-foreground">{tr(l,"Vanavond · 20:00–04:00 · Trainingslocatie","Tonight · 20:00–04:00 · Training Venue","Ce soir · 20:00–04:00 · Lieu d’entraînement","Heute Abend · 20:00–04:00 · Trainingsort")}</p></section>
  {assigned&&<section className="grid gap-3 md:grid-cols-3"><article className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted-foreground">{tr(l,"Toegewezen werkplek","Assigned workplace","Poste attribué","Zugewiesener Arbeitsplatz")}</p><p className="text-xl font-black">{workplace}</p><p>{role==="responsible_lead"?tr(l,"Verantwoordelijke","Responsible","Responsable","Verantwortlich"):tr(l,"Barpersoneel","Bar staff","Personnel du bar","Barpersonal")}</p></article><article className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted-foreground">{tr(l,"Mijn shift","My shift","Mon shift","Meine Schicht")}</p><p className="text-xl font-black">20:00–04:00</p><p>{state.stage==="working"||state.stage==="resumed"?tr(l,"Aan het werk","Working","Au travail","Bei der Arbeit"):state.stage==="break"?tr(l,"Pauze","Break","Pause","Pause"):tr(l,"Gepland","Scheduled","Planifié","Geplant")}</p></article><article className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted-foreground">{tr(l,"Briefing","Briefing","Briefing","Briefing")}</p><p className="font-black">{state.briefing?tr(l,"Bevestigd","Confirmed","Confirmé","Bestätigt"):tr(l,"Nog te bevestigen","Confirmation required","À confirmer","Noch zu bestätigen")}</p></article></section>}
  {assigned&&<section className="rounded-2xl border bg-card p-4"><h2 className="font-black">{tr(l,"Team · Hoofdbar","Team · Main Bar","Équipe · Bar principal","Team · Hauptbar")}</h2><div className="mt-2 space-y-1"><p>{userName} · {tr(l,"Training","Training","Formation","Training")}</p><p>{tr(l,"Alex Demo","Alex Demo","Alex Demo","Alex Demo")} · {tr(l,"Verantwoordelijke","Responsible","Responsable","Verantwortlich")}</p><p>{tr(l,"Sam Demo","Sam Demo","Sam Demo","Sam Demo")} · {tr(l,"Barpersoneel","Bar staff","Personnel du bar","Barpersonal")}</p></div></section>}
  <button type="button" disabled={state.stage==="finished"} onClick={action} className="w-full rounded-xl bg-violet-600 p-4 font-black text-white disabled:opacity-60">{button}</button>
  {state.stage==="finished"&&<button type="button" onClick={()=>{sessionStorage.removeItem(KEY);save({stage:"event",briefing:false})}} className="w-full rounded-xl border p-3 font-bold">{tr(l,"OPLEIDING OPNIEUW STARTEN","RESTART TRAINING","RECOMMENCER LA FORMATION","TRAINING NEU STARTEN")}</button>}
  {note&&<div className="fixed inset-x-3 bottom-[calc(5rem+env(safe-area-inset-bottom))] z-[160] rounded-2xl border border-violet-500/40 bg-background p-4 shadow-2xl"><p className="font-bold">{note}</p><button type="button" onClick={()=>setNote("")} className="mt-3 rounded-lg border px-3 py-2 text-sm font-bold">{tr(l,"BEGREPEN","GOT IT","COMPRIS","VERSTANDEN")}</button></div>}
 </main>
}