"use client"
import {useEffect,useMemo,useState} from "react"
import {parseUiLocale,LANGUAGE_APPLIED_EVENT} from "@/lib/locale-preferences"
type Locale="nl"|"en"|"fr"|"de"; type Phase="assigned"|"checked_in"|"working"|"break"|"finished"
const tr=(l:Locale,nl:string,en:string,fr:string,de:string)=>({nl,en,fr,de}[l])
export function SandboxOperations({userName,role}:{userName:string;role:string}){
 const [locale,setLocale]=useState<Locale>("nl"),[phase,setPhase]=useState<Phase>("assigned"),[seconds,setSeconds]=useState(0)
 useEffect(()=>{const on=(e:Event)=>{const x=parseUiLocale((e as CustomEvent<string>).detail);if(x)setLocale(x as Locale)};const x=parseUiLocale(document.documentElement.lang);if(x)queueMicrotask(()=>setLocale(x as Locale));addEventListener(LANGUAGE_APPLIED_EVENT,on);return()=>removeEventListener(LANGUAGE_APPLIED_EVENT,on)},[])
 useEffect(()=>{if(phase!=="working"&&phase!=="break")return;const id=setInterval(()=>setSeconds(v=>v+1),1000);return()=>clearInterval(id)},[phase])
 const time=useMemo(()=>new Date(seconds*1000).toISOString().slice(11,19),[seconds])
 const guide=phase==="assigned"?tr(locale,"Je bent ingepland op Main Bar. Klik op Check-in om je aanwezigheid te registreren.","You are scheduled at Main Bar. Tap Check-in to register your arrival.","Vous êtes planifié au Bar principal. Appuyez sur Check-in pour enregistrer votre arrivée.","Du bist an der Hauptbar eingeplant. Tippe auf Check-in, um deine Ankunft zu registrieren."):phase==="checked_in"?tr(locale,"Check-in is bevestigd. Start nu je werk; vanaf dan loopt je werktimer.","Check-in is confirmed. Start work now; your work timer will begin.","Le check-in est confirmé. Commencez maintenant le travail ; le minuteur démarrera.","Check-in bestätigt. Starte jetzt die Arbeit; dann beginnt dein Arbeitstimer."):phase==="working"?tr(locale,"Je bent aan het werk. De timer loopt. Start een pauze of beëindig je werk.","You are working and the timer is running. Start a break or finish work.","Vous travaillez et le minuteur tourne. Démarrez une pause ou terminez.","Du arbeitest und der Timer läuft. Starte eine Pause oder beende die Arbeit."):phase==="break"?tr(locale,"Je pauzetimer loopt. Stop de pauze om terug te keren naar je werktimer.","Your break timer is running. End the break to return to your work timer.","Le minuteur de pause tourne. Terminez la pause pour reprendre le travail.","Dein Pausentimer läuft. Beende die Pause, um zur Arbeitszeit zurückzukehren."):tr(locale,"Shift afgerond. Je uren zouden nu ter controle worden ingediend.","Shift complete. Your hours would now be submitted for review.","Shift terminé. Vos heures seraient maintenant soumises au contrôle.","Schicht beendet. Deine Stunden würden jetzt zur Prüfung eingereicht.")
 const status=phase==="assigned"?tr(locale,"Ingepland","Assigned","Planifié","Eingeplant"):phase==="checked_in"?tr(locale,"Ingecheckt","Checked in","Enregistré","Eingecheckt"):phase==="working"?tr(locale,"Aan het werk","Working","Au travail","Bei der Arbeit"):phase==="break"?tr(locale,"Pauze","Break","Pause","Pause"):tr(locale,"Afgerond","Finished","Terminé","Beendet")
 return <main className="mx-auto max-w-4xl space-y-4 p-4 md:p-8" data-tour-demo="operations">
  <section className="rounded-2xl border border-violet-500/40 bg-violet-500/5 p-4"><p className="text-xs font-black uppercase tracking-[.16em] text-violet-500">{tr(locale,"TRAINING SANDBOX · LOPEND EVENEMENT","TRAINING SANDBOX · LIVE EVENT","SANDBOX D’ENTRAÎNEMENT · ÉVÉNEMENT ACTIF","TRAININGS-SANDBOX · AKTIVES EVENT")}</p><h1 className="mt-1 text-2xl font-black">{tr(locale,"UpTillDawn Trainingsavond","UpTillDawn Training Night","Soirée d’entraînement UpTillDawn","UpTillDawn Trainingsabend")}</h1><p className="mt-1 text-sm">{userName} · {role==="admin"?"Admin":role==="responsible_lead"?tr(locale,"Verantwoordelijke","Responsible","Responsable","Verantwortlich"):tr(locale,"Personeel","Staff","Personnel","Personal")} · {tr(locale,"Hoofdbar","Main Bar","Bar principal","Hauptbar")} · 20:00–04:00</p></section>
  <section className="rounded-2xl border p-4" data-tour-demo="guide"><p className="text-xs font-black uppercase text-violet-500">{tr(locale,"Wat moet je nu doen?","What should you do now?","Que devez-vous faire maintenant ?","Was musst du jetzt tun?")}</p><p className="mt-2 text-sm">{guide}</p></section>
  <section className="grid gap-3 sm:grid-cols-3"><article className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{tr(locale,"Jouw status","Your status","Votre statut","Dein Status")}</p><p className="mt-1 font-black">{status}</p></article><article className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{tr(locale,"Werkplek","Workplace","Poste","Arbeitsplatz")}</p><p className="mt-1 font-black">Main Bar</p><p className="text-sm">20:00–04:00</p></article><article className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{phase==="break"?tr(locale,"Pauzetimer","Break timer","Minuteur pause","Pausentimer"):tr(locale,"Werktimer","Work timer","Minuteur travail","Arbeitstimer")}</p><p className="mt-1 text-2xl font-black tabular-nums">{time}</p></article></section>
  <section className="rounded-2xl border p-4" data-tour-demo="time-actions"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{phase==="assigned"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("checked_in")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"INCHECKEN","CHECK IN","CHECK-IN","EINCHECKEN")}</button>}{phase==="checked_in"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("working")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"START WERK","START WORK","COMMENCER","ARBEIT STARTEN")}</button>}{phase==="working"&&<><button data-tour-demo="primary-action" onClick={()=>setPhase("break")} className="rounded-xl border p-3 font-black">{tr(locale,"START PAUZE","START BREAK","DÉMARRER PAUSE","PAUSE STARTEN")}</button><button onClick={()=>setPhase("finished")} className="rounded-xl border p-3 font-black">{tr(locale,"STOP WERK","STOP WORK","ARRÊTER","ARBEIT STOPPEN")}</button></>}{phase==="break"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("working")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"STOP PAUZE","END BREAK","FIN DE PAUSE","PAUSE BEENDEN")}</button>}{phase==="finished"&&<button onClick={()=>{setPhase("assigned");setSeconds(0)}} className="rounded-xl border p-3 font-black">{tr(locale,"OPNIEUW TESTEN","TRY AGAIN","RECOMMENCER","ERNEUT TESTEN")}</button>}</div></section>
  <p className="text-xs text-muted-foreground">{tr(locale,"Alle acties op dit scherm bestaan alleen in deze sandbox en schrijven niets naar de productiedatabase.","Every action on this screen exists only in this sandbox and writes nothing to the production database.","Toutes les actions de cet écran restent dans cette sandbox et n’écrivent rien dans la base de production.","Alle Aktionen auf diesem Bildschirm existieren nur in dieser Sandbox und schreiben nichts in die Produktionsdatenbank.")}</p>
 </main>
}