"use client"
import {useEffect,useMemo,useState} from "react"
import {activeUiLocale,LANGUAGE_APPLIED_EVENT} from "@/lib/locale-preferences"
type Locale="nl"|"en"|"fr"|"de"; type Phase="assigned"|"checked_in"|"working"|"task"|"break"|"resumed"|"incident"|"finished"|"timesheet"
const tr=(l:Locale,nl:string,en:string,fr:string,de:string)=>({nl,en,fr,de}[l])
export function SandboxOperations({userName,role}:{userName:string;role:string}){
 const [locale,setLocale]=useState<Locale>(()=>typeof window==="undefined"?"nl":activeUiLocale() as Locale),[phase,setPhase]=useState<Phase>("assigned"),[seconds,setSeconds]=useState(0)
 useEffect(()=>{const on=()=>setLocale(activeUiLocale() as Locale);addEventListener(LANGUAGE_APPLIED_EVENT,on);return()=>removeEventListener(LANGUAGE_APPLIED_EVENT,on)},[])
 useEffect(()=>{if(phase!=="working"&&phase!=="break")return;const id=setInterval(()=>setSeconds(v=>v+1),1000);return()=>clearInterval(id)},[phase])
 const time=useMemo(()=>new Date(seconds*1000).toISOString().slice(11,19),[seconds])
 const guide=phase==="assigned"?tr(locale,"Check in bij je verantwoordelijke.","Check in with your responsible lead.","Faites votre check-in auprès de votre responsable.","Checke bei deiner verantwortlichen Person ein."):phase==="checked_in"?tr(locale,"Check-in bevestigd. Start nu je werk.","Check-in confirmed. Start work now.","Check-in confirmé. Commencez maintenant votre travail.","Check-in bestätigt. Starte jetzt deine Arbeit."):phase==="working"?tr(locale,"Je werktimer loopt. Open nu je eerste taak.","Your work timer is running. Open your first task.","Votre minuteur de travail tourne. Ouvrez maintenant votre première tâche.","Dein Arbeitstimer läuft. Öffne jetzt deine erste Aufgabe."):phase==="task"?tr(locale,"Taak uitgevoerd. Start nu je verplichte pauze.","Task completed. Start your required break now.","Tâche terminée. Commencez maintenant votre pause obligatoire.","Aufgabe erledigt. Starte jetzt deine vorgeschriebene Pause."):phase==="break"?tr(locale,"Je pauzetimer loopt. Beëindig de pauze om verder te werken.","Your break timer is running. End the break to resume work.","Votre minuteur de pause tourne. Terminez la pause pour reprendre le travail.","Dein Pausentimer läuft. Beende die Pause, um weiterzuarbeiten."):phase==="resumed"?tr(locale,"Je bent opnieuw aan het werk. Open nu Help/Incident om te leren hoe je een probleem meldt.","You are working again. Open Help/Incident to learn how to report a problem.","Vous travaillez à nouveau. Ouvrez Aide/Incident pour apprendre à signaler un problème.","Du arbeitest wieder. Öffne Hilfe/Vorfall, um zu lernen, wie du ein Problem meldest."):phase==="incident"?tr(locale,"Incident gemeld. Rond nu je werk af.","Incident reported. Now finish your work.","Incident signalé. Terminez maintenant votre travail.","Vorfall gemeldet. Beende jetzt deine Arbeit."):phase==="finished"?tr(locale,"Werk gestopt. Controleer en dien nu je urenstaat in.","Work stopped. Review and submit your timesheet now.","Travail arrêté. Vérifiez et soumettez maintenant votre feuille d’heures.","Arbeit beendet. Prüfe und sende jetzt deinen Stundenzettel."):tr(locale,"Urenstaat ingediend. De shifttraining is afgerond.","Timesheet submitted. The shift training is complete.","Feuille d’heures soumise. La formation du shift est terminée.","Stundenzettel eingereicht. Das Schichttraining ist abgeschlossen.")
 const status=phase==="assigned"?tr(locale,"Ingepland","Assigned","Planifié","Eingeplant"):phase==="checked_in"?tr(locale,"Ingecheckt","Checked in","Enregistré","Eingecheckt"):phase==="break"?tr(locale,"Pauze","Break","Pause","Pause"):phase==="finished"||phase==="timesheet"?tr(locale,"Afgerond","Finished","Terminé","Beendet"):tr(locale,"Aan het werk","Working","Au travail","Bei der Arbeit")
 return <main className="mx-auto max-w-4xl space-y-4 p-4 md:p-8" data-tour-demo="operations">
  <section className="rounded-2xl border border-violet-500/40 bg-violet-500/5 p-4"><p className="text-xs font-black uppercase tracking-[.16em] text-violet-500">{tr(locale,"TRAINING SANDBOX · LOPEND EVENEMENT","TRAINING SANDBOX · LIVE EVENT","SANDBOX D’ENTRAÎNEMENT · ÉVÉNEMENT ACTIF","TRAININGS-SANDBOX · AKTIVES EVENT")}</p><h1 className="mt-1 text-2xl font-black">{tr(locale,"UpTillDawn Trainingsavond","UpTillDawn Training Night","Soirée d’entraînement UpTillDawn","UpTillDawn Trainingsabend")}</h1><p className="mt-1 text-sm">{userName} · {role==="admin"?"Admin":role==="responsible_lead"?tr(locale,"Verantwoordelijke","Responsible","Responsable","Verantwortlich"):tr(locale,"Personeel","Staff","Personnel","Personal")} · {tr(locale,"Hoofdbar","Main Bar","Bar principal","Hauptbar")} · 20:00–04:00</p></section>
  <section className="rounded-2xl border p-4" data-tour-demo="guide"><p className="text-xs font-black uppercase text-violet-500">{tr(locale,"Wat moet je nu doen?","What should you do now?","Que devez-vous faire maintenant ?","Was musst du jetzt tun?")}</p><p className="mt-2 text-sm">{guide}</p></section>
  <section className="grid gap-3 sm:grid-cols-3"><article className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{tr(locale,"Jouw status","Your status","Votre statut","Dein Status")}</p><p className="mt-1 font-black">{status}</p></article><article className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{tr(locale,"Werkplek","Workplace","Poste","Arbeitsplatz")}</p><p className="mt-1 font-black">Main Bar</p><p className="text-sm">20:00–04:00</p></article><article className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{phase==="break"?tr(locale,"Pauzetimer","Break timer","Minuteur pause","Pausentimer"):tr(locale,"Werktimer","Work timer","Minuteur travail","Arbeitstimer")}</p><p className="mt-1 text-2xl font-black tabular-nums">{time}</p></article></section>
  <section className="rounded-2xl border p-4" data-tour-demo="time-actions"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
   {phase==="assigned"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("checked_in")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"INCHECKEN","CHECK IN","CHECK-IN","EINCHECKEN")}</button>}
   {phase==="checked_in"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("working")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"START WERK","START WORK","COMMENCER LE TRAVAIL","ARBEIT STARTEN")}</button>}
   {phase==="working"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("task")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"TAAK OPENEN","OPEN TASK","OUVRIR LA TÂCHE","AUFGABE ÖFFNEN")}</button>}
   {phase==="task"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("break")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"TAAK VOLTOOID · START PAUZE","TASK COMPLETE · START BREAK","TÂCHE TERMINÉE · DÉMARRER PAUSE","AUFGABE ERLEDIGT · PAUSE STARTEN")}</button>}
   {phase==="break"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("resumed")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"STOP PAUZE","END BREAK","FIN DE PAUSE","PAUSE BEENDEN")}</button>}
   {phase==="resumed"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("incident")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"HELP / INCIDENT","HELP / INCIDENT","AIDE / INCIDENT","HILFE / VORFALL")}</button>}
   {phase==="incident"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("finished")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"STOP WERK","STOP WORK","ARRÊTER LE TRAVAIL","ARBEIT STOPPEN")}</button>}
   {phase==="finished"&&<button data-tour-demo="primary-action" onClick={()=>setPhase("timesheet")} className="rounded-xl bg-violet-600 p-3 font-black text-white">{tr(locale,"URENSTAAT INDIENEN","SUBMIT TIMESHEET","SOUMETTRE LA FEUILLE D’HEURES","STUNDENZETTEL SENDEN")}</button>}
   {phase==="timesheet"&&<button onClick={()=>{setPhase("assigned");setSeconds(0)}} className="rounded-xl border p-3 font-black">{tr(locale,"TRAINING OPNIEUW","RESTART TRAINING","RECOMMENCER LA FORMATION","TRAINING NEU STARTEN")}</button>}
  </div></section>
  <p className="text-xs text-muted-foreground">{tr(locale,"Alle acties op dit scherm bestaan alleen in deze sandbox en schrijven niets naar de productiedatabase.","Every action on this screen exists only in this sandbox and writes nothing to the production database.","Toutes les actions de cet écran restent dans cette sandbox et n’écrivent rien dans la base de production.","Alle Aktionen auf diesem Bildschirm existieren nur in dieser Sandbox und schreiben nichts in die Produktionsdatenbank.")}</p>
 </main>
}