'use client'

export type OfflineOperationsSnapshot={version:1;userId:string;savedAt:number;events:Array<{id:string;name:string}>;workplaces:Array<{id:string;event_id:string;name:string}>;shifts:Array<{id:string;event_id:string;workplace_id:string;role_name:string|null;scheduled_start:string;scheduled_end:string}>;activeSession:{id:string;event_id:string;shift_id:string|null;started_at:string}|null;activeBreak:{id:string;work_session_id:string;started_at:string}|null;checkins:Array<{event_id:string;workplace_id:string;status:string}>}
export type OfflineBriefing={id:string;title:string;body:string;version:number;event_id:string;kind:'general'|'personal'}
export type OfflineTask={id:string;title:string;description:string|null;status:string;event_id:string;workplace_id:string|null}
export type OfflineEmergencyInfo={event_id:string;event_name:string;event_address:string;emergency_number:string;first_aid_contact:string|null;security_contact:string|null;assembly_point:string|null;procedure:string|null;updated_at:string}
export type OfflineDocument={key:string;userId:string;id:string;event_id:string;event_name:string;kind:string;title:string;description:string|null;file_name:string;mime_type:string;storage_path:string;updated_at:string;blob:Blob}
export type OfflineEvent={id:string;name:string;address:string|null;start_at:string;end_at:string;status:string}
export type OfflineWorkplace={id:string;event_id:string;name:string;description:string|null}
export type OfflineShift={id:string;event_id:string;workplace_id:string;role_name:string;scheduled_start:string;scheduled_end:string;status:string;response_status:string}
export type OfflineIncident={id:string;event_id:string;workplace_id:string|null;message:string;status:string;created_at:string;acknowledged_at:string|null;resolved_at:string|null;escalated_at:string|null}
export type OfflineChecklistItem={id:string;label:string;required:boolean;requires_photo:boolean;completed_at:string|null}
export type OfflineChecklist={id:string;event_id:string;workplace_id:string;kind:string;title:string;description:string|null;status:string;completed_at:string|null;items:OfflineChecklistItem[]}
export type OfflineInventoryItem={id:string;event_id:string;workplace_id:string;name:string;category:string|null;available_quantity:number;issued_quantity:number;damaged_quantity:number;missing_quantity:number}
export type OfflineInventoryIssue={id:string;item_id:string;user_id:string;outstanding_quantity:number;issued_at:string}
export type OfflineKnowledgeArticle={id:string;event_id:string|null;workplace_id:string|null;category:string|null;title:string;body:string;updated_at:string}
export type OfflineContentSnapshot={userId:string;savedAt:number;briefings:OfflineBriefing[];tasks:OfflineTask[];emergency:OfflineEmergencyInfo[];events:OfflineEvent[];workplaces:OfflineWorkplace[];shifts:OfflineShift[];incidents:OfflineIncident[];checklists:OfflineChecklist[];inventoryItems:OfflineInventoryItem[];inventoryIssues:OfflineInventoryIssue[];knowledge:OfflineKnowledgeArticle[]}

function openShellDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('uptilldawn-offline-shell',1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('snapshots'))db.createObjectStore('snapshots',{keyPath:'userId'});if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function openContentDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('uptilldawn-offline-content',2);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('content'))db.createObjectStore('content',{keyPath:'userId'});if(!db.objectStoreNames.contains('documents'))db.createObjectStore('documents',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}

export async function saveOperationsSnapshot(snapshot:OfflineOperationsSnapshot){const db=await openShellDb();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(['snapshots','meta'],'readwrite');tx.objectStore('snapshots').put(snapshot);tx.objectStore('meta').put({key:'activeUserId',value:snapshot.userId});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}

async function mergeContent(userId:string,patch:Partial<Pick<OfflineContentSnapshot,'briefings'|'tasks'|'emergency'|'events'|'workplaces'|'shifts'|'incidents'|'checklists'|'inventoryItems'|'inventoryIssues'|'knowledge'>>){const db=await openContentDb();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('content','readwrite');const store=tx.objectStore('content');const request=store.get(userId);request.onsuccess=()=>{const previous=request.result as OfflineContentSnapshot|undefined;store.put({userId,savedAt:Date.now(),briefings:patch.briefings??previous?.briefings??[],tasks:patch.tasks??previous?.tasks??[],emergency:patch.emergency??previous?.emergency??[],events:patch.events??previous?.events??[],workplaces:patch.workplaces??previous?.workplaces??[],shifts:patch.shifts??previous?.shifts??[],incidents:patch.incidents??previous?.incidents??[],checklists:patch.checklists??previous?.checklists??[],inventoryItems:patch.inventoryItems??previous?.inventoryItems??[],inventoryIssues:patch.inventoryIssues??previous?.inventoryIssues??[],knowledge:patch.knowledge??previous?.knowledge??[]})};request.onerror=()=>reject(request.error);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
export async function saveOfflineBriefings(userId:string,briefings:OfflineBriefing[]){return mergeContent(userId,{briefings})}
export async function saveOfflineTasks(userId:string,tasks:OfflineTask[]){return mergeContent(userId,{tasks})}
export async function saveOfflineBrowseData(userId:string,events:OfflineEvent[],workplaces:OfflineWorkplace[],shifts:OfflineShift[]){return mergeContent(userId,{events,workplaces,shifts})}
export async function saveOfflineOperationalData(userId:string,incidents:OfflineIncident[],checklists:OfflineChecklist[],inventoryItems:OfflineInventoryItem[],inventoryIssues:OfflineInventoryIssue[]){return mergeContent(userId,{incidents,checklists,inventoryItems,inventoryIssues})}
export async function saveOfflineKnowledge(userId:string,knowledge:OfflineKnowledgeArticle[]){return mergeContent(userId,{knowledge})}

export async function clearOfflineIdentity(){const shell=await openShellDb();let userId='';try{await new Promise<void>((resolve,reject)=>{const tx=shell.transaction('meta','readwrite');const store=tx.objectStore('meta');const request=store.get('activeUserId');request.onsuccess=()=>{userId=request.result?.value||'';store.delete('activeUserId')};request.onerror=()=>reject(request.error);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{shell.close()}if(!userId)return;const content=await openContentDb();try{await new Promise<void>((resolve,reject)=>{const tx=content.transaction(['content','documents'],'readwrite');tx.objectStore('content').delete(userId);const docs=tx.objectStore('documents');const request=docs.getAllKeys();request.onsuccess=()=>{for(const key of request.result)if(typeof key==='string'&&key.startsWith(userId+':'))docs.delete(key)};request.onerror=()=>reject(request.error);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{content.close()}}


export async function saveOfflineEmergency(userId:string,emergency:OfflineEmergencyInfo[]){return mergeContent(userId,{emergency})}

export async function loadOfflineDocuments(userId:string){const db=await openContentDb();try{const rows=await new Promise<OfflineDocument[]>((resolve,reject)=>{const request=db.transaction('documents').objectStore('documents').getAll();request.onsuccess=()=>resolve((request.result as OfflineDocument[]).filter(row=>row.userId===userId));request.onerror=()=>reject(request.error)});return rows}finally{db.close()}}
export async function replaceOfflineDocuments(userId:string,documents:OfflineDocument[]){const db=await openContentDb();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('documents','readwrite');const store=tx.objectStore('documents');const request=store.getAllKeys();request.onsuccess=()=>{for(const key of request.result){if(typeof key==='string'&&key.startsWith(userId+':'))store.delete(key)}for(const document of documents)store.put(document)};request.onerror=()=>reject(request.error);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
