'use client'

export type OfflineOperationsSnapshot={version:1;userId:string;savedAt:number;events:Array<{id:string;name:string}>;workplaces:Array<{id:string;event_id:string;name:string}>;shifts:Array<{id:string;event_id:string;workplace_id:string;role_name:string|null;scheduled_start:string;scheduled_end:string}>;activeSession:{id:string;event_id:string;shift_id:string|null;started_at:string}|null;activeBreak:{id:string;work_session_id:string;started_at:string}|null;checkins:Array<{event_id:string;workplace_id:string;status:string}>}
export type OfflineBriefing={id:string;title:string;body:string;version:number;event_id:string;kind:'general'|'personal'}
export type OfflineTask={id:string;title:string;description:string|null;status:string;event_id:string;workplace_id:string|null}
export type OfflineContentSnapshot={userId:string;savedAt:number;briefings:OfflineBriefing[];tasks:OfflineTask[]}

function openShellDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('uptilldawn-offline-shell',1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('snapshots'))db.createObjectStore('snapshots',{keyPath:'userId'});if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function openContentDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open('uptilldawn-offline-content',1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('content'))db.createObjectStore('content',{keyPath:'userId'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}

export async function saveOperationsSnapshot(snapshot:OfflineOperationsSnapshot){const db=await openShellDb();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(['snapshots','meta'],'readwrite');tx.objectStore('snapshots').put(snapshot);tx.objectStore('meta').put({key:'activeUserId',value:snapshot.userId});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}

async function mergeContent(userId:string,patch:Partial<Pick<OfflineContentSnapshot,'briefings'|'tasks'>>){const db=await openContentDb();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('content','readwrite');const store=tx.objectStore('content');const request=store.get(userId);request.onsuccess=()=>{const previous=request.result as OfflineContentSnapshot|undefined;store.put({userId,savedAt:Date.now(),briefings:patch.briefings??previous?.briefings??[],tasks:patch.tasks??previous?.tasks??[]})};request.onerror=()=>reject(request.error);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
export async function saveOfflineBriefings(userId:string,briefings:OfflineBriefing[]){return mergeContent(userId,{briefings})}
export async function saveOfflineTasks(userId:string,tasks:OfflineTask[]){return mergeContent(userId,{tasks})}

export async function clearOfflineIdentity(){const db=await openShellDb();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('meta','readwrite');tx.objectStore('meta').delete('activeUserId');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
