-- New approved personnel must complete their own profile before the first role tour.
alter table public.profiles add column if not exists app_profile_required boolean not null default false;
alter table public.profiles add column if not exists app_profile_completed_at timestamptz;
create or replace function public.upt_current_profile_completion() returns table(required boolean,completed boolean) language sql security definer set search_path=public,pg_temp stable as $$ select p.app_profile_required,(not p.app_profile_required or p.app_profile_completed_at is not null) from public.profiles p where p.id=auth.uid() $$;
revoke all on function public.upt_current_profile_completion() from public,anon; grant execute on function public.upt_current_profile_completion() to authenticated;
create or replace function public.upt_mark_own_profile_complete() returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ declare p public.profiles%rowtype; begin if auth.uid() is null then raise exception 'Aanmelden vereist.'; end if; select * into p from public.profiles where id=auth.uid(); if p.id is null then raise exception 'Profiel niet gevonden.'; end if; if nullif(trim(p.full_name),'') is null or nullif(trim(p.home_address),'') is null or nullif(trim(p.phone_number),'') is null or p.date_of_birth is null or nullif(trim(p.national_register_number),'') is null or nullif(trim(p.iban),'') is null or nullif(trim(p.profile_photo_url),'') is null then raise exception 'Vul eerst alle verplichte profielvelden en een profielfoto in.'; end if; update public.profiles set app_profile_completed_at=coalesce(app_profile_completed_at,now()),updated_at=now() where id=auth.uid(); return true; end $$;
revoke all on function public.upt_mark_own_profile_complete() from public,anon; grant execute on function public.upt_mark_own_profile_complete() to authenticated;
create or replace function public.upt_require_first_profile(p_user uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.upt_is_admin(auth.uid()) then raise exception 'Geen toegang.'; end if; update public.profiles set app_profile_required=true,app_profile_completed_at=null where id=p_user; end $$;
revoke all on function public.upt_require_first_profile(uuid) from public,anon; grant execute on function public.upt_require_first_profile(uuid) to authenticated;
notify pgrst,'reload schema';